[project]
name = "backend_local"
requires-python = ">=3.9,<3.14"
version = "0.1.0"
dependencies = [
    "dagster==1.11.12",
    "dagster-webserver",
    "dagster-dg-cli",
    "dagster-duckdb>=0.27.12",
]

[tool.dg]
directory_type = "deployment"


