# .github/workflows/deploy.yml
name: Deploy to University VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to VM
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        script: |
          # Navigate to project directory
          cd ~/complex-stories
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm ci --only=production
          
          # Build the application
          npm run build
          
          # Restart PM2 process
          pm2 restart complex-stories
          
          # Check status
          pm2 status
          
          echo "Deployment completed successfully!"