# .github/workflows/deploy.yml
name: Deploy to University VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Setup SSH Key
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VM
      if: github.ref == 'refs/heads/main'
      run: |
        ssh -i ~/.ssh/deploy_key ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
          # Navigate to project directory
          cd ~/complex-stories
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm ci --only=production
          
          npm install
          
          # Build the application
          npm run build
          
          # Restart PM2 process
          pm2 restart complex-stories
          
          # Check status
          pm2 status
          
          echo "Deployment completed successfully!"
        EOF